language: node_js
node_js:
  - "10"

cache:
  directories:
    - node_modules

branches:
  only:
    - master

install:
  - npm install -g firebase-tools
  - npm install
  - npm --prefix functions install

script:
  - firebase deploy --token $FIREBASE_TOKEN
  